### ISSUE TITLE
zip does not contain all images of a collection or an album

### ISSUE THREAD

**Issue by Mandip70** [mistic100/Piwigo-BatchDownloader#16] opened 2017-05-12 22:45 UTC
Hello Mistic,

thank you for your engagement and your work!
I have the problem, that the zip file does not contain all images of an album. PclZip or the usage of a collection for download did not change the behavior. All images are visable for "Everybody".

Downloader version: 2.2.2
Environment:
Piwigo 2.9.0
Operating system: Linux
PHP: 5.5.38-nmm2 (Show info) [2017-05-13 00:40:53]
 (tried also php 7.0)
MySQL: 5.7.15-nmm5-log [2017-05-13 00:40:53]
Graphics Library: ImageMagick 6.8.9-9

two albums:
114 images, 112 in zip
163 images, 19 in zip
Tried to download "Original" or "Large"

I hope you can solve this topic!

thank you an best regards,
Manfred

**Comment by Mandip70** [comment] 2017-05-12 22:56
The problem seems to be the filesize, if there is an image larger than 5,7 MB (do not know the exact problem size), this file and all others after it ar not added to the zip.

**Comment by canalnoises** [comment] 2017-05-19 17:49
I'm having this issue too. Any update on a solution?

**Comment by mistic100** [comment] 2017-05-19 18:10
Sorry I cannot investigate on this. I can only say it looks like a limitation of the server but I don't know which and where to look.

**Comment by canalnoises** [comment] 2017-05-20 19:23
Hmm. Well, maybe we can start collecting data, at least? This is a rather serious problem that pretty much destroys the utility of what would otherwise be an excellent plugin that would be worth supporting financially... 

@mistic100, could you tell us what kind of server setups you know to work so @Mandip70 and I can compare to what we're running on?

Here's my environment:
Piwigo 2.9.0
Server OS: Linux
PHP version: 5.6.29
ImageMagick 6.6.9-7
MySQL 5.6

**Comment by canalnoises** [comment] 2017-05-20 22:41
By happenstance I came across a [bug report](https://github.com/plegall/Piwigo-download_permissions/issues/1) by @plegall on the Download Permissions plugin saying that having it activated makes Batch Downloader not work. I had Download Permissions installed and active, but I didn't see any change in Batch Downloader's behavior after deactivating and deleting Download Permissions. Are there any other plugins that are known to be incompatible with Batch Downloader?

Here's a list of the plugins I have installed and active on my Piwigo:
- Admin Tools
- Back2Front
- Batch Downloader
- Community
- Crop Image
- Extended Description
- facetag
- Forecast
- gdThumb
- Icy Modify Picture
- LocalFiles Editor
- Manage Properties Photos
- Photo added by
- Photo Update
- Rotate Image
- RV autocomplete
- RV Thumb Scroller
- SmartAlbums
- Take A Tour of Your Piwigo
- User Collections
- User Mass Register
- User Tags

**Comment by plegall** [comment] 2017-05-24 13:32
It may be related to #15 with the new case insensitivity. I've sent a Pull-Request :-)

**Comment by canalnoises** [comment] 2017-05-25 04:56
@plegall I think you did it! I just manually applied your fix, and so far Batch Downloader appears to be  working again! I'm going to try to find time to do some more extensive testing tomorrow, but I'm pretty encouraged by what I'm seeing so far. Thanks for your work!

**Comment by mistic100** [comment] 2017-05-29 17:46
The fix has been released

**Closed by mistic100** 2017-05-29 17:46 UTC

**Comment by Mandip70** [comment] 2017-05-29 21:01
Thank you very much, it works!

**Comment by canalnoises** [comment] 2017-05-31 02:21
Yes, I've confirmed that it's working great for me too. Thanks @plegall for figuring this out, and thanks @mistic100 for building such a great plugin!
